Medacademy/Models/AccountViewModels.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Medacademy.Models
{
    public class ExternalLoginConfirmationViewModel
    {
        [Required]
        [Display(Name = "Email")]
        public string Email { get; set; }
    }

    public class ExternalLoginListViewModel
    {
        public string ReturnUrl { get; set; }
    }

    public class SendCodeViewModel
    {
        public string SelectedProvider { get; set; }
        public ICollection<System.Web.Mvc.SelectListItem> Providers { get; set; }
        public string ReturnUrl { get; set; }
        public bool RememberMe { get; set; }
    }

    public class VerifyCodeViewModel
    {
        [Required]
        public string Provider { get; set; }

        [Required]
        [Display(Name = "Code")]
        public string Code { get; set; }
        public string ReturnUrl { get; set; }

        [Display(Name = "Remember this browser?")]
        public bool RememberBrowser { get; set; }

        public bool RememberMe { get; set; }
    }

    public class ForgotViewModel
    {
        [Required]
        [Display(Name = "Email")]
        public string Email { get; set; }
    }

    public class LoginViewModel
    {
        [Required]
        [Display(Name = "Email")]
        [EmailAddress]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [Display(Name = "Remember me?")]
        public bool RememberMe { get; set; }
    }

    public class RegisterViewModel
    {
        [Required]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm password")]
        [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }

    public class ResetPasswordViewModel
    {
        [Required]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm password")]
        [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }

        public string Code { get; set; }
    }

    public class ForgotPasswordViewModel
    {
        [Required]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }
    }
}

Medacademy/Models/Login.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Medacademy.Models
{

    public class Login
    {
        [Required(ErrorMessage = "Required")]
        [EmailAddress(ErrorMessage = "Entered e-mail is not a valid mail")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Required")]
        public string Password { get; set; }

    }
}

Medacademy/Controllers/AccountController.cs
using System;
using System.Globalization;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using Medacademy.Models;

namespace Medacademy.Controllers
{
    [Authorize]
    public class AccountController : Controller
    {
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;

        public AccountController()
        {
        }

        public AccountController(ApplicationUserManager userManager, ApplicationSignInManager signInManager )
        {
            UserManager = userManager;
            SignInManager = signInManager;
        }

        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set 
            { 
                _signInManager = value; 
            }
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        //
        // GET: /Account/Login
        [AllowAnonymous]
        public ActionResult Login(string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;
            return View();
        }

        //
        // POST: /Account/Login
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Login(LoginViewModel model, string returnUrl)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            // This doesn't count login failures towards account lockout
            // To enable password failures to trigger account lockout, change to shouldLockout: true
            var result = await SignInManager.PasswordSignInAsync(model.Email, model.Password, model.RememberMe, shouldLockout: false);
            switch (result)
            {
                case SignInStatus.Success:
                    return RedirectToLocal(returnUrl);
                case SignInStatus.LockedOut:
                    return View("Lockout");
                case SignInStatus.RequiresVerification:
                    return RedirectToAction("SendCode", new { ReturnUrl = returnUrl, RememberMe = model.RememberMe });
                case SignInStatus.Failure:
                default:
                    ModelState.AddModelError("", "Invalid login attempt.");
                    return View(model);
            }
        }

        //
        // GET: /Account/VerifyCode
        [AllowAnonymous]
        public async Task<ActionResult> VerifyCode(string provider, string returnUrl, bool rememberMe)
        {
            // Require that the user has already logged in via username/password or external login
            if (!await SignInManager.HasBeenVerifiedAsync())
            {
                return View("Error");
            }
            return View(new VerifyCodeViewModel { Provider = provider, ReturnUrl = returnUrl, RememberMe = rememberMe });
        }

        //
        // POST: /Account/VerifyCode
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> VerifyCode(VerifyCodeViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            // The following code protects for brute force attacks against the two factor codes. 
            // If a user enters incorrect codes for a specified amount of time then the user account 
            // will be locked out for a specified amount of time. 
            // You can configure the account lockout settings in IdentityConfig
            var result = await SignInManager.TwoFactorSignInAsync(model.Provider, model.Code, isPersistent:  model.RememberMe, rememberBrowser: model.RememberBrowser);
            switch (result)
            {
                case SignInStatus.Success:
                    return RedirectToLocal(model.ReturnUrl);
                case SignInStatus.LockedOut:
                    return View("Lockout");
                case SignInStatus.Failure:
                default:
                    ModelState.AddModelError("", "Invalid code.");
                    return View(model);
            }
        }

        //
        // GET: /Account/Register
        [AllowAnonymous]
        public ActionResult Register()
        {
            return View();
        }

        //
        // POST: /Account/Register
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Register(RegisterViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = new ApplicationUser { UserName = model.Email, Email = model.Email };
                var result = await UserManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    await SignInManager.SignInAsync(user, isPersistent:false, rememberBrowser:false);
                    
                    // For more information on how to enable account confirmation and password reset please visit http://go.microsoft.com/fwlink/?LinkID=320771
                    // Send an email with this link
                    // string code = await UserManager.GenerateEmailConfirmationTokenAsync(user.Id);
                    // var callbackUrl = Url.Action("ConfirmEmail", "Account", new { userId = user.Id, code = code }, protocol: Request.Url.Scheme);
                    // await UserManager.SendEmailAsync(user.Id, "Confirm your account", "Please confirm your account by clicking <a href=\"" + callbackUrl + "\">here</a>");

                    return RedirectToAction("Index", "Home");
                }
                AddErrors(result);
            }

            // If we got this far, something failed, redisplay form
            return View(model);
        }

        //
        // GET: /Account/ConfirmEmail
        [AllowAnonymous]
        public async Task<ActionResult> ConfirmEmail(string userId, string code)
        {
            if (userId == null || code == null)
            {
                return View("Error");
            }
            var result = await UserManager.ConfirmEmailAsync(userId, code);
            return View(result.Succeeded ? "ConfirmEmail" : "Error");
        }

        //
        // GET: /Account/ForgotPassword
        [AllowAnonymous]
        public ActionResult ForgotPassword()
        {
            return View();
        }

        //
        // POST: /Account/ForgotPassword
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ForgotPassword(ForgotPasswordViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = await UserManager.FindByNameAsync(model.Email);
                if (user == null || !(await UserManager.IsEmailConfirmedAsync(user.Id)))
                {
                    // Don't reveal that the user does not exist or is not confirmed
                    return View("ForgotPasswordConfirmation");
                }

                // For more information on how to enable account confirmation and password reset please visit http://go.microsoft.com/fwlink/?LinkID=320771
                // Send an email with this link
                // string code = await UserManager.GeneratePasswordResetTokenAsync(user.Id);
                // var callbackUrl = Url.Action("ResetPassword", "Account", new { userId = user.Id, code = code }, protocol: Request.Url.Scheme);		
                // await UserManager.SendEmailAsync(user.Id, "Reset Password", "Please reset your password by clicking <a href=\"" + callbackUrl + "\">here</a>");
                // return RedirectToAction("ForgotPasswordConfirmation", "Account");
            }

            // If we got this far, something failed, redisplay form
            return View(model);
        }

        //
        // GET: /Account/ForgotPasswordConfirmation
        [AllowAnonymous]
        public ActionResult ForgotPasswordConfirmation()
        {
            return View();
        }

        //
        // GET: /Account/ResetPassword
        [AllowAnonymous]
        public ActionResult ResetPassword(string code)
        {
            return code == null ? View("Error") : View();
        }

        //
        // POST: /Account/ResetPassword
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ResetPassword(ResetPasswordViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            var user = await UserManager.FindByNameAsync(model.Email);
            if (user == null)
            {
                // Don't reveal that the user does not exist
                return RedirectToAction("ResetPasswordConfirmation", "Account");
            }
            var result = await UserManager.ResetPasswordAsync(user.Id, model.Code, model.Password);
            if (result.Succeeded)
            {
                return RedirectToAction("ResetPasswordConfirmation", "Account");
            }
            AddErrors(result);
            return View();
        }

        //
        // GET: /Account/ResetPasswordConfirmation
        [AllowAnonymous]
        public ActionResult ResetPasswordConfirmation()
        {
            return View();
        }

        //
        // POST: /Account/ExternalLogin
        [HttpPost]
        [AllowAnonymous]

Medacademy/Controllers/AccountsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Medacademy.Models;
using Ma.ClassLibrary;
using Ma.EntityLibrary;


namespace Medacademy.Controllers
{
    public class AccountsController : Controller
    {
        public DateTime CurrentTime = TimeZoneInfo.ConvertTimeFromUtc(System.DateTime.Now.ToUniversalTime(), TimeZoneInfo.FindSystemTimeZoneById("India Standard Time"));
        public MAEntities _Entities = new MAEntities();
        // GET: Accounts
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Courses()
        {
            return View();
        }
        public ActionResult Packages()
        {
            return View();
        }
        public ActionResult Preparation()
        {
            return View();
        }
        public ActionResult Reports()
        {
            return View();
        }
        public ActionResult Groups()
        {
            return View();
        }
        public ActionResult AboutUs()
        {
            return View();
        }
        public ActionResult ContactUs()
        {
            return View();
        }
        public ActionResult Login()
        {
            return View();
        }
        public ActionResult SignUp()
        {
            return View();
        }
        public ActionResult LoginCheck(Login model)
        {
            try
            {
                var user = _Entities.tb_Login.Where(x => x.Email.ToLower() == model.Email.ToLower() && x.Password == model.Password && x.IsActive == true).FirstOrDefault();
                if (user != null)
                {

                    if (user.RoleId == 1)
                    {

                        return Json(new { status = true, msg = "Success", userType = 1 }, JsonRequestBehavior.AllowGet);
                    }
                    else if (user.RoleId == 2)
                    {

                        return Json(new { status = true, msg = "Success", userType = 2 }, JsonRequestBehavior.AllowGet);
                    }
                    else
                    {
                        return Json(new { status = false, msg = "Username/Password does not match" }, JsonRequestBehavior.AllowGet);
                    }

                }
                else
                {
                    return Json(new { status = false, msg = "Username/Password incorrect" }, JsonRequestBehavior.AllowGet);

                }

            }
            catch (Exception ex)
            {
                return Json(new { status = false, msg = ex.InnerException.InnerException }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

Medacademy/Views/Accounts/AboutUs.cshtml
@{
    ViewBag.Title = "AboutUs";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<section class="breadcrumbsSection about_section">
    <div class="container">
        <div class="row">
            <div class="col-12">

                <div class="breadcrumbs">
                    <h1>About us</h1>
                    <ul>
                        <li><a href="/Accounts/Index">Home</a></li>
                        <li>Courses</li>
                    </ul>
                </div><!-- ./breadcrumbs -->

            </div>
        </div>
    </div>
</section>
<!-- ./breadcrumbsSection -->

<section class="abt_cnts commSec">
    <div class="container">
        <div class="col-12">
            <div class="inner_pgs">
                <div class="row">
                    <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">
                        <div class="cont_sideimg">
                            <img src="~/Content/images/about/about1.jpg">
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">
                        <h3 class="mainTitle blckClr left_ttl">Our History</h3>
                        <div class="details_his">
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eius mod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehe derit in voluptate velit esse cillum.</p>

                            <p>On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot fore see the pain and trouble that are bound to belongs to who fail in their duty.</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="inner_pgs">
                <div class="row">
                    <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">
                        <h3 class="mainTitle blckClr left_ttl">Our Mission</h3>
                        <div class="details_his">
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eius mod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehe derit in voluptate velit esse cillum.</p>

                            <p>On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot fore see the pain and trouble that are bound to belongs to who fail in their duty.</p>
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">
                        <div class="row">
                            <div class="col-6">
                                <div class="cont_sideimg right">
                                    <img src="~/Content/images/about/about2.jpg">
                                </div>
                            </div>
                            <div class="col-6">
                                <div class="cont_sideimg right">
                                    <img src="~/Content/images/about/about3.jpg">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="inner_pgs">
                <div class="row">
                    <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">
                        <h3 class="mainTitle blckClr left_ttl">Our Vision</h3>
                        <div class="details_his">
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eius mod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehe derit in voluptate velit esse cillum.</p>

                            <p>On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot fore see the pain and trouble that are bound to belongs to who fail in their duty.</p>
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">
                        <div class="cont_sideimg">
                            <img src="~/Content/images/about/about4.jpg">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

Medacademy/Views/Accounts/ContactUs.cshtml
@{
    ViewBag.Title = "ContactUs";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<section class="breadcrumbsSection uppercontact_section">
    <div class="container">
        <div class="row">
            <div class="col-12">

                <div class="breadcrumbs">
                    <h1>Contact Us</h1>
                    <ul>
                        <li><a href="/Accounts/Index">Home</a></li>
                        <li>Contact Us</li>
                    </ul>
                </div><!-- ./breadcrumbs -->

            </div>
        </div>
    </div>
</section>
<!-- ./breadcrumbsSection -->

<section class="contact_sction commSec">
    <div class="container">
        <div class="col-12">
            <div class="connecting_pg">
                <div class="row">
                    <div class="col-lg-8 col-md-8 col-sm-12">
                        <div class="left_white">
                            <h4 class="contact_title">Want to know more about Medacademy and its programs ?</h4>
                            <p>Just write to us using the response from below.</p>
                            <div class="contact_forms">
                                <div class="form-group">
                                    <label for="Name">Name<sup style="color: #f00;">*</sup></label>
                                    <input type="text" class="form-control inner_label" placeholder="Your full name">
                                </div>
                                <div class="form-group">
                                    <label for="email">Email<sup style="color: #f00;">*</sup></label>
                                    <input type="email" class="form-control inner_label" placeholder="Your e-mail address">
                                </div>
                            </div>
                            <div class="contact_forms">
                                <div class="form-group">
                                    <label>Contact Number<sup style="color: #f00;">*</sup></label>
                                    <input type="text" class="form-control inner_label" placeholder="Your contact number">
                                </div>
                                <div class="form-group">
                                    <label>School<sup style="color: #f00;">*</sup></label>
                                    <input type="email" class="form-control inner_label" placeholder="Name of your school">
                                </div>
                            </div>
                            <div class="messagbx">
                                <div class="form-group">
                                    <label>Message<sup style="color: #f00;">*</sup></label>
                                    <textarea class="form-control inner_label" placeholder="Type your message here"></textarea>
                                </div>
                                <div class="mail_btn">
                                    <a href="#"><img src="~/Content/images/send_btn.png"></a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-4 col-sm-12 blue_sec">
                        <div class="right_blue">
                            <h4 class="white_right">Reach us</h4>
                            <div class="contact_loc">
                                <div class="loc_img">
                                    <img src="~/Content/images/contact_single.png" class="filter">
                                </div>
                                <div>
                                    <p>503 Old Buffalo Street<br>Northwest #205, New York-3087</p>
                                </div>
                            </div>
                            <div class="contact_loc">
                                <div class="loc_img">
                                    <img src="~/Content/images/phone_single.png" class="filter">
                                </div>
                                <div>
                                    <p>+3453-909-6565<br>+2390-875-2235</p>
                                </div>
                            </div>
                            <div class="contact_loc">
                                <div class="loc_img">
                                    <img src="~/Content/images/mail_single.png" class="filter">
                                </div>
                                <div>
                                    <p>medacademy.co.in@gmail.com</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

Medacademy/Views/Accounts/Login.cshtml
@model Medacademy.Models.Login
@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_LoginLayout.cshtml";
}


<section class="lgn_sec">

    @using (Ajax.BeginForm("LoginCheck", "Accounts", null, new AjaxOptions
    {
        HttpMethod = "POST",
        OnSuccess = "LoginCheckSuccess",
        OnFailure = "LoginCheckFailed"
    }, new { id = "form-login" }))
    {
        <div class="container">
            <div class="row">
                <div class="col-12 full_wid">
                    <div class="cust_lg_form">
                        <div class="details">

                            <h4>Login!</h4>
                            <div class="form-group">
                                @*<input type="text" class="form-control" placeholder="Email">*@
                                @Html.TextBoxFor(m => m.Email, new { @class = "form-control", placeholder = "Email" })
                                @Html.ValidationMessageFor(m => m.Email)
                            </div>
                            <div class="form-group">
                                @*<input type="text" class="form-control" placeholder="Password">*@
                                @Html.PasswordFor(m => m.Password, new { @class = "form-control", placeholder = "Password" })
                                @Html.ValidationMessageFor(m => m.Password)
                            </div>
                            <p>Don’t  have an account ?  <span><a href="/Accounts/SignUp">Sign up</a> </span></p>
                            <div class="sb_btn form-group">
                                @*<a href="#">login</a>*@
                                <button type="submit" class="btn-class">Login</button>
                            </div>

                        </div>


                        <div class="blue_right_sec">
                            <div class="img_cont">
                                <img src="~/Content/images/login/lgo.png">
                            </div>
                            <h4>
                                WELCOME TO
                                MEDACADEMY
                            </h4>
                            <p class="hid">To keep connected with us please signup with peronal info</p>
                            <div class="sb_btn form-group ">
                                <a href="/Accounts/SignUp">Sign up</a>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    }
</section>



        <script>
            function LoginCheckSuccess(result) {
               // alert("test");
                //debugger;
                if (result.status) {
                    if (result.userType == 1) {
                        //toastr.info(result.msg);
                         window.location.href = '/Admin/Dashboard';
                    }
                    else if (result.userType == 2) {

                        // window.location.href = '/Parent/Home';
                    }
                }
                else {
                    //$('#errorMsg').removeClass("isHidden");
                    toastrError(result.msg);
                }
            }
            function LoginCheckFailed(result) {
                toastrError(result.msg);
            }


            //$(document).ready(function () {

            //    alert("test");

            //});


        </script>
   
@*<script>
   
    </script>*@

Medacademy/Views/Accounts/Preparation.cshtml
@{
    ViewBag.Title = "Preparation";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Preparation</h2>